# Generated by Django 2.2.4 on 2020-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='codename',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código para control interno'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
