# Generated by Django 2.2.4 on 2020-04-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20200401_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cate', to='directorio.Categorias', verbose_name='Categoría'),
        ),
    ]
