# Generated by Django 2.2.4 on 2020-04-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_directorio_fecha_r'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorias',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='directorio',
            options={'ordering': ['nombre']},
        ),
    ]
