# Generated by Django 2.2.4 on 2020-04-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_auto_20200402_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='serv_dom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='repartidores',
            field=models.ManyToManyField(null=True, to='directorio.Repartidores', verbose_name='Repartidores'),
        ),
    ]
