# Generated by Django 2.2.4 on 2020-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_auto_20200402_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='repartidores',
            field=models.ManyToManyField(to='directorio.Repartidores', verbose_name='Repartidores'),
        ),
    ]
