# Generated by Django 2.2.4 on 2020-05-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_auto_20200402_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='web_page',
            field=models.URLField(blank=True, null=True, verbose_name='Link a página web'),
        ),
    ]
